### PR TITLE
Bump DPMJET to master and include CMake and Scoring

### PR DESCRIPTION
**Pull request by mbroz84**
I took master of upstream DPMJET, then cherry-picked:
https://github.com/DPMJET/DPMJET/commit/e1a864b1a4c9f96141f423b3717e246ac2fa85a6
https://github.com/DPMJET/DPMJET/commit/a20aa015cabd35dd400a6d2a95b1f1bf9e11a5e2
https://github.com/DPMJET/DPMJET/commit/b173450e64d96da032a41a28dde4f3c5cbea6cb0

For second I fixed simple conflict in src/dpmjet/DT_KKEVNT.f keeping changes from upstream and the scoring. Tried to compile AliRoot with this version, works OK.

### CODE REVIEW

**Comment by sawenzel** [comment]
Thanks @mbroz84. We'll take a look.

**Comment by jackal1-66** [comment]
@mbroz84 I checked the cherry picking and tested the build locally. It works, however could you please edit the CMakeLists.txt to reflect the changes in https://github.com/DPMJET/DPMJET/commit/8288b303c43551a4350bffdd71c6427f44e0833e? The use of GLOB was avoided there and the same should be done in this PR.

**Comment by mbroz84** [comment]
@jackal1-66 Change done

**Comment by jackal1-66** [comment]
Thank you @mbroz84. The building works locally on slc9. I think it can now be merged and a new tag should be created (v19.3.7-alice1)

**Comment by mbroz84** [comment]
I added a line to install headers by Cmake instead in the alidist recipe

**Comment by jackal1-66** [comment]
Fine for me, @ktf could you take a look, merge if everything's fine and create the new v19.3.7-alice1 tag?

**Comment by pzhristov** [comment]
Hi @mbroz84 
Please check PR#8, it keeps the history and adresses all the changes you made without cherry-picks, so it should be easier to merge new changes form the upstream repository. If everything is Ok, please close this PR.

**Comment by mbroz84** [comment]
Hi @pzhristov, PR#8 looks good to me. Closing here.

**Pull request closed without merging**
